/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const incidents_Logic = require('./code/incidents-logic');
const incidents_Logic2 = require('./code/incidents-logic2');
const incidents_Logic3 = require('./code/incidents-logic3');

class incidentapp07Srv extends LCAPApplicationService {
    async init() {

        this.on('CREATE', 'Incidents', async (request, next) => {
            await incidents_Logic(request);
            return next();
        });

        this.on('CREATE', 'Incidents', async (request, next) => {
            await incidents_Logic2(request);
            return next();
        });

        this.before('CREATE', 'Incidents', async (request) => {
            await incidents_Logic3(request);
        });

        return super.init();
    }
}


module.exports = {
    incidentapp07Srv
};